name: flutter_gradient_generator
description: A new Flutter project.
homepage: fluttergradientgenerator.com
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.9"
  
dependencies:
  flutter:
    sdk: flutter
  # The original package, https://pub.dev/packages/flutter_vector_icons, does not support
  # icon tree shaking. This is my fork of the original package with fixes for icon tree shaking.
  flutter_vector_icons: 
    git: 
      url: https://github.com/victoreronmosele/flutter-vector-icons.git
      ref: v3.0.0
  collection: ^1.15.0
  url_strategy: ^0.2.0
  quiver: ^3.0.1+1
  google_fonts: ^4.0.3
  url_launcher: ^6.0.12
  firebase_core: ^2.7.1
  firebase_analytics: ^10.1.5
  provider: ^6.0.5
  web_color_picker: 
  tinycolor2: ^3.0.1
  meta: ^1.10.0
  screenshot: ^2.1.0
  image_downloader_web: ^2.0.4
  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

