import 'dart:collection';

import 'package:flutter/foundation.dart';
import 'package:flutter_gradient_generator/data/app_typedefs.dart';
import 'package:flutter_gradient_generator/models/abstract_gradient.dart';

/// A view model that manages the history of the gradients generated by the user.
class HistoryViewModel with ChangeNotifier {
  HistoryViewModel({
    required this.onUndoOrRedo,
  });

  /// Called when an undo or redo action is performed.
  final void Function() onUndoOrRedo;

  /// The current list of gradients in the history affected by the undo and
  /// redo actions.
  final List<AbstractGradient> _liveHistory = [];

  /// The current list of gradients in the history affected by the undo and
  /// redo actions.
  UnmodifiableListView<AbstractGradient> get liveHistory =>
      UnmodifiableListView(_liveHistory);

  /// The list of gradients that have been removed as a result of an undo action.
  final List<AbstractGradient> _removedGradients = [];

  /// The list of gradients that have been removed as a result of an undo action.
  UnmodifiableListView<AbstractGradient> get removedGradients =>
      UnmodifiableListView(_removedGradients);

  /// The list of [TimeStampedGradient]s that have been generated by the user
  /// from the start of the app to the current point.
  ///
  /// This list is not affected by the undo and redo actions.
  final List<TimeStampedGradient> _fullHistory = [];

  /// The list of [TimeStampedGradient]s that have been generated by the user
  /// from the start of the app to the current point.
  ///
  /// This list is not affected by the undo and redo actions.
  UnmodifiableListView<TimeStampedGradient> get fullHistory =>
      UnmodifiableListView(_fullHistory);

  /// Adds a new gradient to the live history and the full history.
  void addNewGradientToHistory(AbstractGradient gradient) {
    _liveHistory.add(gradient);

    final timeStampedGradient = (
      gradient: gradient,
      timeStamp: DateTime.now(),
    );

    _fullHistory.add(timeStampedGradient);

    _removedGradients.clear();

    notifyListeners();
  }

  /// Removes the last gradient from the live history and adds it to the list of
  /// removed gradients.
  void undo() {
    if (_liveHistory.isEmpty) {
      return;
    }

    final removedGradient = _liveHistory.removeLast();
    _removedGradients.add(removedGradient);

    notifyListeners();

    onUndoOrRedo();
  }

  /// Removes the last gradient from the list of removed gradients and adds it
  /// back to the live history.
  void redo() {
    if (_removedGradients.isEmpty) {
      return;
    }

    final lastRemovedGradient = _removedGradients.removeLast();
    _liveHistory.add(lastRemovedGradient);

    notifyListeners();

    onUndoOrRedo();
  }
}
